###################################################################
# Visualization Library in R for DDGs generated by RDataTracker
#
# Author: Luis A. Perez
# Late-Updated: May 16th, 2016
####################################################################

library(igraph)

# Loads a DDG into memory for visualization purposes.
load.ddg <- function(ddg.path) {
  infile <- paste()
}

# Visualize a given ddg in memory representation
visualize.ddg <- function(ddg) {

}